export const GET_ROOM_DATA_REQUEST = 'GET_ROOM_DATA_REQUEST'
export const GET_ROOM_DATA_SUCCESS = 'GET_ROOM_DATA_SUCCESS'
export const GET_ROOM_DATA_FAILURE = 'GET_ROOM_DATA_FAILURE'

export const JOIN_ROOM_REQUEST = 'JOIN_ROOM_REQUEST'
export const JOIN_ROOM_SUCCESS = 'JOIN_ROOM_SUCCESS'
export const JOIN_ROOM_FAILURE = 'JOIN_ROOM_FAILURE'

export const REACT_REQUEST = 'REACT_REQUEST'
export const REACT_SUCCESS = 'REACT_SUCCESS'
export const REACT_FAILURE = 'REACT_FAILURE'

export const LEAVE_ROOM_SUCCESS = 'LEAVE_ROOM_SUCCESS'
