export const JOIN_ROOM_REQUEST = 'SOCKET/JOIN_ROOM_REQUEST'
export const JOIN_ROOM_SUCCESS = 'SOCKET/JOIN_ROOM_SUCCESS'
export const JOIN_ROOM_FAILURE = 'SOCKET/JOIN_ROOM_FAILURE'

export const GET_ROOM_DATA_REQUEST = 'SOCKET/GET_ROOM_DATA_REQUEST'
export const GET_ROOM_DATA_SUCCESS = 'SOCKET/GET_ROOM_DATA_SUCCESS'
export const GET_ROOM_DATA_FAILURE = 'SOCKET/GET_ROOM_DATA_FAILURE'

export const REACT_REQUEST = 'SOCKET/REACT_REQUEST'
export const REACT_SUCCESS = 'SOCKET/REACT_SUCCESS'
export const REACT_FAILURE = 'SOCKET/REACT_FAILURE'

export const LEAVE_ROOM_SUCCESS = 'SOCKET/LEAVE_ROOM_SUCCESS'